image: gradle:9.4.0-jdk25
stages:
  - test
  - publish

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

test:
    stage: test
    script:
        - gradle test
    artifacts:
        when: always
        reports:
          junit: build/test-results/test/*.xml
        paths:
        - build/reports/tests/test

publish:
  stage: publish
  script:
    - gradle publish
  only:
    - main